### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by msoxzw** [aiortc/pylsqpack#14]
Memory leak occurs, at least for Python 3.10.3 on Windows.

```
import pylsqpack

for _ in range(65536):
    decoder = pylsqpack.Decoder(4096, 16)
    del decoder

```
```
import pylsqpack

for _ in range(65536):
    encoder = pylsqpack.Encoder()
    del encoder

```

**Comment by msoxzw** [comment]
Additionally, "https://github.com/aiortc/aioquic/blob/main/src/aioquic/_buffer.c" and "https://github.com/aiortc/aioquic/blob/main/src/aioquic/_crypto.c" suffer memory leak, as well.

**Comment by jlaine** [comment]
Let's just focus on pylsqpack, issues in aioquic are out of scope and should be reported in the correct repository.

**Comment by msoxzw** [comment]
I feel sorry that I have not yet run valgrind.

After running aforementioned code snippet, `pylsqpack.Decoder` will occupy approximately 300 MiB memory, and `pylsqpack.Encoder` will occupy roughly 550 MiB memory, which should be released.

In addition, from above memory consumption log generated by a long-running process, not only `pylsqpack.Decoder`, `pylsqpack.Encoder`, but also `pylsqpack.Decoder.feed_header`, `pylsqpack.Decoder.resume_header`, do not release nontrivial memory that is no longer needed.

**Comment by jlaine** [comment]
Hi @msoxzw could you try #15 and let me know if it fixes your issue?

**Comment by msoxzw** [comment]
It has not yet been completely fixed.

First, `pylsqpack.Decoder` and `pylsqpack.Encoder` still do not free some memory which is much less than the prior's

Second, `pylsqpack.Decoder.feed_header`, `pylsqpack.Decoder.resume_header`, and `pylsqpack.Encoder.encode` do not release memory, as well.

Third, it is worthy to investigate the memory allocation and de-allocation of every methods in `pylsqpack.Decoder` and `pylsqpack.Encoder`.
